import type { BlogPost, BlogCategory } from './blog-service';

// Mock blog categories
export const mockCategories: BlogCategory[] = [
  {
    id: '1',
    name: 'Education',
    slug: 'education',
    description: 'Educational content and resources',
    color: '#3B82F6',
    postCount: 15,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Technology',
    slug: 'technology',
    description: 'Technology in education',
    color: '#10B981',
    postCount: 8,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Career',
    slug: 'career',
    description: 'Career guidance and tips',
    color: '#F59E0B',
    postCount: 12,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// Mock blog posts
export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'The Future of Education: How Technology is Transforming Learning',
    slug: 'future-of-education-technology-transforming-learning',
    excerpt: 'Explore how modern technology is revolutionizing the way we learn and teach, from AI-powered tutoring to virtual reality classrooms.',
    content: 'Full article content here...',
    type: 'ARTICLE' as any,
    status: 'PUBLISHED' as any,
    visibility: 'PUBLIC' as any,
    authorId: '1',
    schoolId: '1',
    categoryId: '1',
    tags: ['education', 'technology', 'future', 'learning'],
    featuredImage: 'https://via.placeholder.com/400x200/3B82F6/FFFFFF?text=Education+Technology',
    mediaUrls: [],
    readTime: 8,
    viewCount: 1250,
    likeCount: 45,
    commentCount: 12,
    shareCount: 8,
    isLiked: false,
    isBookmarked: false,
    isShared: false,
    isFeatured: true,
    isPinned: false,
    publishedAt: '2024-01-15T10:00:00Z',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    author: {
      id: '1',
      name: 'Dr. Sarah Johnson',
      avatar: 'https://via.placeholder.com/40/3B82F6/FFFFFF?text=SJ',
      bio: 'Education Technology Expert',
      role: 'Professor',
      school: {
        id: '1',
        name: 'Harvard University',
      },
    },
    school: {
      id: '1',
      name: 'Harvard University',
      logo: 'https://via.placeholder.com/40/3B82F6/FFFFFF?text=HU',
    },
    category: mockCategories[0],
    comments: [],
    likes: [],
    shares: [],
  },
  {
    id: '2',
    title: '5 Essential Skills Every Student Should Develop in 2024',
    slug: '5-essential-skills-every-student-should-develop-2024',
    excerpt: 'Discover the most important skills students need to succeed in today\'s rapidly changing world.',
    content: 'Full article content here...',
    type: 'GUIDE' as any,
    status: 'PUBLISHED' as any,
    visibility: 'PUBLIC' as any,
    authorId: '2',
    schoolId: '2',
    categoryId: '3',
    tags: ['skills', 'development', 'students', 'career'],
    featuredImage: 'https://via.placeholder.com/400x200/10B981/FFFFFF?text=Essential+Skills',
    mediaUrls: [],
    readTime: 6,
    viewCount: 890,
    likeCount: 32,
    commentCount: 7,
    shareCount: 15,
    isLiked: true,
    isBookmarked: false,
    isShared: false,
    isFeatured: true,
    isPinned: false,
    publishedAt: '2024-01-12T14:30:00Z',
    createdAt: '2024-01-12T14:30:00Z',
    updatedAt: '2024-01-12T14:30:00Z',
    author: {
      id: '2',
      name: 'Michael Chen',
      avatar: 'https://via.placeholder.com/40/10B981/FFFFFF?text=MC',
      bio: 'Career Development Specialist',
      role: 'Career Counselor',
      school: {
        id: '2',
        name: 'Stanford University',
      },
    },
    school: {
      id: '2',
      name: 'Stanford University',
      logo: 'https://via.placeholder.com/40/10B981/FFFFFF?text=SU',
    },
    category: mockCategories[2],
    comments: [],
    likes: [],
    shares: [],
  },
  {
    id: '3',
    title: 'Breaking Down Barriers: Inclusive Education for All',
    slug: 'breaking-down-barriers-inclusive-education-for-all',
    excerpt: 'Learn about the importance of inclusive education and how schools can create welcoming environments for all students.',
    content: 'Full article content here...',
    type: 'ARTICLE' as any,
    status: 'PUBLISHED' as any,
    visibility: 'PUBLIC' as any,
    authorId: '3',
    schoolId: '3',
    categoryId: '1',
    tags: ['inclusive', 'education', 'diversity', 'accessibility'],
    featuredImage: 'https://via.placeholder.com/400x200/F59E0B/FFFFFF?text=Inclusive+Education',
    mediaUrls: [],
    readTime: 10,
    viewCount: 2100,
    likeCount: 78,
    commentCount: 23,
    shareCount: 12,
    isLiked: false,
    isBookmarked: true,
    isShared: false,
    isFeatured: false,
    isPinned: false,
    publishedAt: '2024-01-10T09:15:00Z',
    createdAt: '2024-01-10T09:15:00Z',
    updatedAt: '2024-01-10T09:15:00Z',
    author: {
      id: '3',
      name: 'Dr. Emily Rodriguez',
      avatar: 'https://via.placeholder.com/40/F59E0B/FFFFFF?text=ER',
      bio: 'Special Education Advocate',
      role: 'Director of Special Education',
      school: {
        id: '3',
        name: 'MIT',
      },
    },
    school: {
      id: '3',
      name: 'MIT',
      logo: 'https://via.placeholder.com/40/F59E0B/FFFFFF?text=MIT',
    },
    category: mockCategories[0],
    comments: [],
    likes: [],
    shares: [],
  },
  {
    id: '4',
    title: 'The Rise of Online Learning: What We\'ve Learned',
    slug: 'rise-of-online-learning-what-weve-learned',
    excerpt: 'A comprehensive look at the evolution of online learning and its impact on traditional education.',
    content: 'Full article content here...',
    type: 'NEWS' as any,
    status: 'PUBLISHED' as any,
    visibility: 'PUBLIC' as any,
    authorId: '4',
    schoolId: '1',
    categoryId: '2',
    tags: ['online', 'learning', 'digital', 'education'],
    featuredImage: 'https://via.placeholder.com/400x200/8B5CF6/FFFFFF?text=Online+Learning',
    mediaUrls: [],
    readTime: 7,
    viewCount: 1560,
    likeCount: 56,
    commentCount: 18,
    shareCount: 9,
    isLiked: false,
    isBookmarked: false,
    isShared: false,
    isFeatured: false,
    isPinned: false,
    publishedAt: '2024-01-08T16:45:00Z',
    createdAt: '2024-01-08T16:45:00Z',
    updatedAt: '2024-01-08T16:45:00Z',
    author: {
      id: '4',
      name: 'Prof. David Kim',
      avatar: 'https://via.placeholder.com/40/8B5CF6/FFFFFF?text=DK',
      bio: 'Digital Learning Researcher',
      role: 'Research Professor',
      school: {
        id: '1',
        name: 'Harvard University',
      },
    },
    school: {
      id: '1',
      name: 'Harvard University',
      logo: 'https://via.placeholder.com/40/3B82F6/FFFFFF?text=HU',
    },
    category: mockCategories[1],
    comments: [],
    likes: [],
    shares: [],
  },
  {
    id: '5',
    title: 'Building Resilience: Mental Health Support in Schools',
    slug: 'building-resilience-mental-health-support-in-schools',
    excerpt: 'Understanding the importance of mental health support in educational institutions and practical strategies for implementation.',
    content: 'Full article content here...',
    type: 'ARTICLE' as any,
    status: 'PUBLISHED' as any,
    visibility: 'PUBLIC' as any,
    authorId: '5',
    schoolId: '4',
    categoryId: '1',
    tags: ['mental-health', 'resilience', 'support', 'wellbeing'],
    featuredImage: 'https://via.placeholder.com/400x200/EF4444/FFFFFF?text=Mental+Health',
    mediaUrls: [],
    readTime: 9,
    viewCount: 3200,
    likeCount: 124,
    commentCount: 31,
    shareCount: 22,
    isLiked: true,
    isBookmarked: true,
    isShared: false,
    isFeatured: true,
    isPinned: false,
    publishedAt: '2024-01-05T11:20:00Z',
    createdAt: '2024-01-05T11:20:00Z',
    updatedAt: '2024-01-05T11:20:00Z',
    author: {
      id: '5',
      name: 'Dr. Lisa Wang',
      avatar: 'https://via.placeholder.com/40/EF4444/FFFFFF?text=LW',
      bio: 'Child Psychology Specialist',
      role: 'School Psychologist',
      school: {
        id: '4',
        name: 'Yale University',
      },
    },
    school: {
      id: '4',
      name: 'Yale University',
      logo: 'https://via.placeholder.com/40/EF4444/FFFFFF?text=YU',
    },
    category: mockCategories[0],
    comments: [],
    likes: [],
    shares: [],
  },
];

// Get featured posts (first 3 posts)
export const getFeaturedPosts = (): BlogPost[] => {
  return mockBlogPosts.filter(post => post.isFeatured).slice(0, 3);
};

// Get all posts
export const getAllPosts = (): BlogPost[] => {
  return mockBlogPosts;
};

// Get posts by category
export const getPostsByCategory = (categoryId: string): BlogPost[] => {
  return mockBlogPosts.filter(post => post.categoryId === categoryId);
};

// Get post by ID
export const getPostById = (id: string): BlogPost | undefined => {
  return mockBlogPosts.find(post => post.id === id);
};

// Get post by slug
export const getPostBySlug = (slug: string): BlogPost | undefined => {
  return mockBlogPosts.find(post => post.slug === slug);
};
